server:
  host: "localhost"
  port: 8080
  mode: "debug" # debug, release, test

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "model_collection"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5

jwt:
  secret: "your-secret-key-here"
  expire_hours: 24

app:
  name: "model_collect"
  version: "1.0.0"
  environment: "development" 